services:
  - type: web
    name: library-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
